#!/usr/bin/env bash
# Transfers a file to a server using scp

# Check if exactly 4 parameters are provided
if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# Transfer the file using scp to the user's home directory (~/)
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$server_ip":~/
